version: "3.8"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
      args:
        DEBUG: true
        NODE_ENV: development
        ENVIRONMENT_TYPE: development
    env_file: 
      - ./app/.env.local
    volumes:
      - ./app:/app/cutcutfilm/services/web
      - /app/cutcutfilm/services/web/node_modules
    ports:
      - "3000:3000"