version: "3.8"
services:
  web:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile.dev
    env_file: 
      - ./app/.env.local
    environment:
      - NEXT_PUBLIC_DEBUG=true
      - NODE_ENV=development
      - NEXT_PUBLIC_ENVIRONMENT_TYPE=development
    volumes:
      - ./app:/app/cutcutfilm/services/web
      - /app/cutcutfilm/services/web/node_modules
    ports:
      - "3000:3000"