version: "3.8"
services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file: 
      - ./app/.env.local
    environment:
      - NEXT_PUBLIC_DEBUG=false
      - NODE_ENV=production
      - NEXT_PUBLIC_ENVIRONMENT_TYPE=production
    ports:
      - "3000:3000"
