apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.web.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.services.web.name }}
  replicas: {{ .Values.services.web.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.services.web.name }}
    spec:
      containers:
        - name: {{ .Values.services.web.name }}
          image: {{ .Values.services.web.image }}
          env:
            - name: NODE_ENV
              value: "production"
          ports:
            - containerPort: {{ .Values.services.web.containerPort }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}