namespace: "cutcutfilm-dev"
name: "cutcutfilm-web-dev"

host: "ccf-dev.vidrox.me"

imagePullSecrets: [{ name: cutcutfilm-ghcr }]

services:
  web:
    replicas: 1
    path: "/"
    name: "cutcutfilm-web-dev"
    secretName: "ccf-dev-secret"
    image: ""
    containerPort: 3000
    