namespace: "cutcutfilm"
name: "cutcutfilm-web"

host: "cutcutfilm.com"

debug: false
environmentType: "production"
apiUrl: "https://cutcutfilm.com/gql"

imagePullSecrets: [{ name: cutcutfilm-ghcr }]

services:
  web:
    replicas: 1
    path: "/"
    name: "cutcutfilm-web"
    secretName: "ccf-secret"
    image: ""
    containerPort: 3000