namespace: "cutcutfilm-dev"
name: "cutcutfilm-web-dev"

host: "ccf-dev.vidrox.me"

debug: true
environmentType: "development"
apiUrl: "https://ccf-dev.vidrox.me/api/gql"

imagePullSecrets: [{ name: cutcutfilm-ghcr }]

services:
  web:
    replicas: 1
    path: "/"
    name: "cutcutfilm-web-dev"
    secretName: "ccf-dev-secret"
    image: ""
    containerPort: 3000
    